<?php
    $title = 'Adicionando nova transição';
    $this->headTitle($title);
?>

<h1><?=$this->escapeHtml($title)?></h1>

<?php

$form->setAttribute('action', $this->url('finances', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);

$id = $this->form->get('id');
$title = $this->form->get('title');
$type = $this->form->get('type');
$price = $this->form->get('price');
$category = $this->form->get('category');

$id->setAttribute('class','form-control');
$title->setAttribute('class','form-control');
$type->setAttribute('class','form-control');
$price->setAttribute('class','form-control');
$category->setAttribute('class','form-control');

$submit = $this->form->get('submit');
$submit->setAttribute('class','btn btn-primary btn-lg');
?>

<?=$this->formElement($id)?>

<div class="form-group">
    <div class="col-md-6">
        <?=$this->formLabel($title)?>
        <?=$this->formElement($title)?>
        <?=$this->formElementErrors()->render($title,['class'=>'help-block'])?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?=$this->formLabel($type)?>
        <?=$this->formElement($type)?>
        <?=$this->formElementErrors()->render($type,['class'=>'help-block'])?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?=$this->formLabel($price)?>
        <?=$this->formElement($price)?>
        <?=$this->formElementErrors()->render($price,['class'=>'help-block'])?>
    </div>
</div>
<div class="form-group">
    <div class="col-md-6">
        <?=$this->formLabel($category)?>
        <?=$this->formElement($category)?>
        <?=$this->formElementErrors()->render($category,['class'=>'help-block'])?>
    </div>
</div>

<div class="row">
    <?=$this->formElement($submit)?>
    <a href="<?=$this->url('finances',['action'=>'index'])?>" class="btn btn-warning btn-lg">
    Voltar</a>
</div>

<?php
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();