<?php

$form->setAttribute('action', $this->url('finances', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);

$id = $this->form->get('id');
$title = $this->form->get('title');
$type = $this->form->get('type');
$price = $this->form->get('price');
$category = $this->form->get('category');

$id->setAttribute('class','form-control');
$title->setAttribute('class','form-control');
$type->setAttribute('class','form-control');
$price->setAttribute('class','form-control');
$category->setAttribute('class','form-control');

$submit = $this->form->get('submit');
$submit->setAttribute('class','btn btn-primary btn-lg');
?>

<?=$this->formElement($id)?>
<div class="container-header">
    <header class="header">
        <img src="<?= $this->basePath('img/logo.svg') ?>" height="28" alt="Go Finances <?= \Application\Module::VERSION ?>"/></a>
        <nav class="navbar navbar-expand-md navbar-dark" role="navigation">
            <ul style="list-style: none;" class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a style="font-weight: bold" class="nav-link" href="<?= $this->url('finances') ?>">Home</a>
                    &nbsp;&nbsp;
                </li>
            </ul>
        </nav>
    </header>
</div>
<div class="wrapper-container">
    <section class="title-container">
        <h1>Adicionando nova transição</h1>
    </section>
</div>
<div class="form-register">
    <div class="input-form-register">
        <div class="form-group">
            <?=$this->formLabel($title)?>
            <?=$this->formElement($title)?>
            <?=$this->formElementErrors()->render($title,['class'=>'help-block'])?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($type)?>
            <?=$this->formElement($type)?>
            <?=$this->formElementErrors()->render($type,['class'=>'help-block'])?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($price)?>
            <?=$this->formElement($price)?>
            <?=$this->formElementErrors()->render($price,['class'=>'help-block'])?>
        </div>
        <div class="form-group">
            <?=$this->formLabel($category)?>
            <?=$this->formElement($category)?>
            <?=$this->formElementErrors()->render($category,['class'=>'help-block'])?>
        </div>
    </div>
    <div class="row button-form-group">
        <?=$this->formElement($submit)?>
        <a style="margin-left: 10px" href="<?=$this->url('finances',['action'=>'index'])?>" class="btn btn-warning btn-lg">
        Voltar</a>
    </div>
</div>
<?php
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();