<?php
    $title = 'Deletando transição';
    $utl   = $this->url('finances', ['action' => 'delete', 'id' => $id]);

    $this->headTitle($title);
?>

<h1><?=$this->escapeHtml($title)?></h1>

<p>
    Você realmente quer deletar a transição
    "<?= $this->escapeHtml($finances->title) ?>" ?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $album->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Sim" />
        <input type="submit" class="btn btn-success" name="del" value="Nao" />
    </div>
</form>
