<?= $this->doctype() ?>

<?php 

    $totalIncome = 0;
    $totalOutcome = 0;

    foreach ($finances as $finance)
    {
        switch($finance->type)
        {
            case 'income':
                $totalIncome += (int) $finance->price;
                break;

            case 'outcome':
                $totalOutcome += (int) $finance->price;
                break;
            default:
                break;
        }
    }

    $total = $totalIncome - $totalOutcome;
?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Go Finances')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/logo.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
        ?>
    </head>
    <body>
        <div class="container-header">
            <header class="header">
                <img src="<?= $this->basePath('img/logo.svg') ?>" height="28" alt="Go Finances <?= \Application\Module::VERSION ?>"/></a>
                <nav class="navbar navbar-expand-md navbar-dark" role="navigation">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('finances') ?>">
                                Home
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('finances',['action'=>'add']) ?>">
                                Adicionar
                            </a>
                        </li>
                    </ul>
                </nav>
            </header>
        </div>
        
        <div class="wrapper-container">
            <section class="card-container">
                <div class="card"> 
                    <header class="header-card">
                        <p class="p-header">Entradas</p>
                        <img src="/img/income.svg" alt="Entradas" />
                    </header>
                    <h1><?=number_format($totalIncome,2,',', '.')?></h1>
                </div>
                <div class="card"> 
                    <header class="header-card">
                        <p>Saídas</p>
                        <img src="/img/outcome.svg" alt="Saidas" />
                    </header>
                    <h1><?=number_format($totalOutcome,2,',', '.')?></h1>
                </div>
                <div class="card" style="background-color: #FF872C; color: #fff"> 
                    <header class="header-card">
                        <p>Total</p>
                        <img src="/img/total.svg" alt="Total" />
                    </header>
                    <h1><?=number_format($total,2,',', '.')?></h1>
                </div>
            </section>
        
            <section class="table-container">
                <table>
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Preço</th>
                            <th>Categoria</th>
                            <th>Data</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>

                    <tbody>
                        <?php foreach ($finances as $finance) : ?>
                            <tr>
                                <td style="color: #363f5f"><?= $this->escapeHtml($finance->title) ?></td>
                                <?php if($finance->type == 'income') : ?>
                                    <td style="color: #12a454">R$ <?= number_format($finance->price,2,',', '.') ?></td>
                                <?php endif; ?>
                                <?php if($finance->type == 'outcome') : ?>
                                    <td style="color: #e83f5b">- R$ <?= number_format($finance->price,2,',', '.') ?></td>
                                <?php endif; ?>
                                <td><?= $this->escapeHtml($finance->category) ?></td>
                                <td><?= date("m/d/Y",strtotime($finance->date)) ?></td>
                                <td>
                                    <a href="<?=$this->url('finances',['action'=>'edit', 'id' => $finance->id])?>">Editar</a>
                                    <a href="<?=$this->url('finances',['action'=>'delete', 'id' => $finance->id])?>">Deletar</a>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </section>
        </div>
    </body>
</html>
